export const seguros = [
  {
    id: 1,
    type: "Seguro Saúde",
    image: "/assets/serviços/seguros/pexels-polina-tankilevitch-5234508.jpg",
    headline: "Proteção para quem mais importa",
    sub: "Planos de saúde acessíveis e sem burocracia.",
    cta: "Conheça os planos",
    href: "/servicos/seguro-saude",
  },
  {
    id: 2,
    type: "Seguro Vida Empresarial",
    image: "/assets/serviços/seguros/vida.webp",
    headline: "Proteja quem faz sua empresa acontecer",
    sub: "Seguro de vida empresarial com cobertura abrangente e customizada.",
    cta: "Conheça os planos",
    href: "/servicos/seguro-vida-empresarial",
  },
  {
    id: 3,
    type: "Seguro Empresarial",
    image: "/assets/serviços/seguros/empresarial.webp",
    headline: "Proteção completa para o seu negócio",
    sub: "Cobertura sob medida para proteger patrimônio, operações e continuidade da empresa.",
    cta: "Conheça os planos",
    href: "/servicos/seguro-empresarial",
  },
  {
    id: 4,
    type: "Seguro Garantia",
    image: "/assets/serviços/seguros/garantia.webp",
    headline: "Mais segurança em contratos e obras",
    sub: "Garante o cumprimento de obrigações contratuais com credibilidade e agilidade.",
    cta: "Conheça os planos",
    href: "/servicos/seguro-garantia",
  },
  {
    id: 5,
    type: "Seguro Responsabilidade Civil",
    image: "/assets/serviços/seguros/responsabilidade-civil.webp",
    headline: "Tranquilidade frente a imprevistos",
    sub: "Proteção contra danos causados a terceiros no exercício da atividade profissional.",
    cta: "Conheça os planos",
    href: "/servicos/seguro-responsabilidade-civil",
  },
];

export const consorcios = [
  {
    id: 1,
    type: "Veículos Pesados",
    image: "/assets/serviços/consorcios/veiculo-pesado-4.webp",
    headline: "Força para grandes conquistas",
    sub: "Consórcio para máquinas e veículos pesados, com planejamento e segurança.",
    cta: "Conheça os planos",
    href: "/servicos/consorcio-veiculos-pesados",
  },
  {
    id: 2,
    type: "Veículos",
    image: "/assets/serviços/consorcios/veiculo.webp",
    headline: "Seu próximo veículo, sem juros",
    sub: "Planeje a compra do seu carro ou moto com parcelas que cabem no bolso.",
    cta: "Conheça os planos",
    href: "/servicos/consorcio-veiculos",
  },
  {
    id: 3,
    type: "Imóvel",
    image: "/assets/serviços/consorcios/imovel-3.webp",
    headline: "O caminho seguro para seu imóvel",
    sub: "Conquiste sua casa ou investimento imobiliário com planejamento e segurança.",
    cta: "Conheça os planos",
    href: "/servicos/consorcio-imoveis",
  },
  {
    id: 4,
    type: "Sustentável",
    image: "/assets/serviços/consorcios/sustentavel-4.webp",
    headline: "Invista no futuro com economia",
    sub: "Consórcio para energia solar e soluções sustentáveis, sem juros.",
    cta: "Conheça os planos",
    href: "/servicos/consorcio-sustentavel",
  },
];
